services:
  - type: web
    name: salesence-backend
    env: node
    plan: free
    region: oregon
    branch: main
    root: .
    buildCommand: >
      npm install -g pnpm && \
      pnpm install && \
      pnpm --filter @scraper/db db:generate && \
      pnpm -r --filter packages/scraper-core build && \
      pnpm -r --filter packages/db build && \
      pnpm --filter apps/api build
    startCommand: pnpm --filter apps/api start
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.cyimsigwvzmoyvqzzcjt:Emrhn.27@aws-0-ap-south-1.pooler.supabase.com:5432/postgres
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5aW1zaWd3dnptb3l2cXp6Y2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODkyNTMsImV4cCI6MjA2OTQ2NTI1M30.xheUwptcjqmhJnFVa6RZBsX6sSM1J9wE39yCnZ3K3YY
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5aW1zaWd3dnptb3l2cXp6Y2p0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1Mzg4OTI1MywiZXhwIjoyMDY5NDY1MjUzfQ.NiNuxSTC6DCDyBmwkft2xqQ-4VuQAXUdSUsbDO2C0i8
